// LITMUS: An Automated Molecular Integrals Generator
// Copyright 2022 Z. Rinkevicius, KTH, Sweden.

#include <gtest/gtest.h>

#include <string>

#include "spherical_momentum_generators.hpp"

namespace {

/// True if haystack contains needle.
bool
contains(const std::string& haystack, const std::string& needle)
{
    return haystack.find(needle) != std::string::npos;
}

}  // namespace

TEST(SphericalMomentumGeneratorTest, EmitsHeaderScaffolding)
{
    const auto text = format_spherical_momentum(2);

    EXPECT_TRUE(contains(text, "#ifndef SphericalMomentum_hpp"));
    EXPECT_TRUE(contains(text, "#define SphericalMomentum_hpp"));
    EXPECT_TRUE(contains(text, "#endif /* SphericalMomentum_hpp */"));
    EXPECT_TRUE(contains(text, "namespace spher_mom {"));
    EXPECT_TRUE(contains(text, "}  // namespace spher_mom"));
    EXPECT_TRUE(contains(text, "transformation_factors(const int component) -> std::vector<std::pair<int, double>>"));
    EXPECT_TRUE(contains(text, "generated by Litmus"));

    // the JCTC 2020 provenance and the VeloxChem license are preserved.
    EXPECT_TRUE(contains(text, "10.1021/acs.jctc.9b01296"));
    EXPECT_TRUE(contains(text, "SPDX-License-Identifier: BSD-3-Clause"));
}

TEST(SphericalMomentumGeneratorTest, EmitsBlocksUpToMaxAngularMomentum)
{
    const auto text = format_spherical_momentum(4);

    EXPECT_TRUE(contains(text, "if constexpr (N == 0)"));
    EXPECT_TRUE(contains(text, "if constexpr (N == 4)"));
    EXPECT_FALSE(contains(text, "if constexpr (N == 5)"));

    EXPECT_TRUE(contains(text, "// S type real solid harmonics"));
    EXPECT_TRUE(contains(text, "// G type real solid harmonics"));

    EXPECT_TRUE(contains(text, "// TODO: Add higher order transformation factors l > 4"));
}

TEST(SphericalMomentumGeneratorTest, SAndPBlocksMatchVeloxChem)
{
    const auto text = format_spherical_momentum(1);

    // S: single unit component on the s Cartesian.
    EXPECT_TRUE(contains(text, "if (component == 0)\n            return {\n                {0, 1.0},\n            };"));

    // P: component order is y, z, x (m = -1, 0, +1) with unit factors.
    EXPECT_TRUE(contains(text, "if (component == 0)\n            return {\n                {1, 1.0},\n            };"));
    EXPECT_TRUE(contains(text, "if (component == 1)\n            return {\n                {2, 1.0},\n            };"));
    EXPECT_TRUE(contains(text, "if (component == 2)\n            return {\n                {0, 1.0},\n            };"));
}

TEST(SphericalMomentumGeneratorTest, DBlockIsByteIdenticalToVeloxChem)
{
    const auto text = format_spherical_momentum(2);

    // For D functions the shared radical is sqrt(3) with unit lead, so the emitted
    // block reproduces VeloxChem's hand-written D block verbatim.
    const std::string expected =
        "    // D type real solid harmonics\n"
        "    if constexpr (N == 2)\n"
        "    {\n"
        "        const double f3 = std::sqrt(3.0);\n"
        "\n"
        "        if (component == 0)\n"
        "            return {\n"
        "                {1, f3},\n"
        "            };\n"
        "        if (component == 1)\n"
        "            return {\n"
        "                {4, f3},\n"
        "            };\n"
        "        if (component == 2)\n"
        "            return {\n"
        "                {0, -0.5},\n"
        "                {3, -0.5},\n"
        "                {5, 1.0},\n"
        "            };\n"
        "        if (component == 3)\n"
        "            return {\n"
        "                {2, f3},\n"
        "            };\n"
        "        if (component == 4)\n"
        "            return {\n"
        "                {0, 0.5 * f3},\n"
        "                {3, -0.5 * f3},\n"
        "            };\n"
        "\n"
        "        return std::vector<std::pair<int, double>>();\n"
        "    }\n";

    EXPECT_TRUE(contains(text, expected));
}

TEST(SphericalMomentumGeneratorTest, FactorsOutSharedRadicalConstants)
{
    const auto text = format_spherical_momentum(4);

    // G functions use sqrt(35), sqrt(70), sqrt(10) and sqrt(5) radicals.
    EXPECT_TRUE(contains(text, "const double f35 = std::sqrt(35.0);"));
    EXPECT_TRUE(contains(text, "const double f70 = std::sqrt(70.0);"));
    EXPECT_TRUE(contains(text, "const double f5 = std::sqrt(5.0);"));
}
